- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      yum:
        name: '*'
        state: latest
        update_cache: yes
      changed_when: False

  tasks:
    - include: tasks/packages.yml
