# sudo yum -y install sonarg |& tee sonarg-install.out

- name: Install sonarg
  #yum: name=sonarg
  yum: name=perl
  register: test
  async: 1200
  poll: 5
- debug:
    msg: "{{ result }}"
- debug:
    msg: "{ test[stdout].split('\n') }}"
- debug:
    var={{ test.stdout }}
- debug:
    msg: "{ test.stdout }}"
- debug: var=test.stdout_lines
- debug: var=test.stdout_lines
- debug:
    msg: "{{ test.stdout }}"
- debug:
    msg: "Now do: `sudo sonarg-setup |& tee sonarg-setup.out`"
