# sudo yum -y install sonarg |& tee sonarg-install.out

- name: Install sonarg
  #yum: name=sonarg
  yum: name=perl
  register: test
  async: 1200
  poll: 5
#rb#- debug:
#rb#    var={{ test[stdout].split('\n') }}
#rb#- debug:
#rb#    var={{ test.stdout }}
- debug: var=test.stdout_lines
- debug: var=test.stdout_lines
- debug:
    msg: "{{ test.stdout }}"
- debug:
    msg: "Now do: `sudo sonarg-setup |& tee sonarg-setup.out`"
